// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tradcvgixuaanyhjjgnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyYWRjdmdpeHVhYW55aGpqZ250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzMxMjYsImV4cCI6MjA2OTgwOTEyNn0.03ly1AzJPZnGNwKMzRrmSww3-jNlqI_dUF_7xD9dK8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});